### ISSUE TITLE
Android failed to build in RN 0.77

### ISSUE THREAD

**Issue by Elabar** [rive-app/rive-react-native#286]
### Description
Build fail with
```
* What went wrong:
Execution failed for task ':rive-react-native:compileDebugKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction
   > Compilation error. See log for more details

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.
```

### Provide a Repro
1. create a new expo project
```
npx create-expo-app@latest StickerSmash
```
2. upgrade packages to use RN 0.77
```
    "@expo/vector-icons": "^14.0.4",
    "react-native": "0.77.0",
    "react-native-gesture-handler": "~2.22.1",
    "react-native-reanimated": "~3.16.7",
    "react-native-safe-area-context": "5.2.0",
    "react-native-screens": "~4.6.0",
    "react-native-web": "~0.19.13",
    "react-native-webview": "13.13.2"
```
3. Run succesfully
```
npx expo prebuild --clean
npx expo run:android
```
4. Add rive library and run again, project fail to build
```
npx expo install rive-react-native
npx expo prebuild --clean
npx expo run:android
```

### Expected behavior
Project should build

#### Additional context
Expo SDK 52 is compatible with react native 0.77. https://expo.dev/changelog/2025/01-21-react-native-0.77

**Comment by SurendraSp** [comment]
* What went wrong:
Execution failed for task ':rive-react-native:compileDebugKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction
   > Compilation error. See log for more details

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

BUILD FAILED in 51s
error Failed to install the app. Command failed with exit code 1: ./gradlew app:installDebug -PreactNativeDevServerPort=8081
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /Users/sp/WebStormProjects/rn-app/node_modules/react-native-video/android/src/main/java/com/brentvatne/exoplayer/ReactExoplayerView.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
e: file:///Users/sp/WebStormProjects/rn-app/node_modules/rive-react-native/android/src/main/java/com/rivereactnative/RiveReactNativeViewManager.kt:33:41 None of the following candidates is applicable:
fun mapToRNLoopMode(loopMode: String): RNLoopMode
fun mapToRNLoopMode(riveLoopMode: Loop): RNLoopMode
e: file:///Users/sp/WebStormProjects/rn-app/node_modules/rive-react-native/android/src/main/java/com/rivereactnative/RiveReactNativeViewManager.kt:34:60 Argument type mismatch: actual type is 'kotlin.String?', but 'kotlin.String' was expected.

**Comment by SurendraSp** [comment]
Temporary Fix

Open RiveReactNativeViewManager.kt File
`your-project/node_modules/rive-react-native/android/src/main/java/com/rivereactnative/RiveReactNativeViewManager.kt`

Add `!!` After all getString()

eg.
Previous
 ```
val animationName = it.getString(0)
 val loopMode = it.getString(1)
 val direction = it.getString(2)
 val isStateMachine = it.getBoolean(3)
```
After Change
```
val animationName = it.getString(0)!!
 val loopMode = it.getString(1)!!
 val direction = it.getString(2)!!
 val isStateMachine = it.getBoolean(3)!!
```

Note: This temporary fix and you have do the changes in all your systems if you using git and node_module is ignored. Also make sure to keep a eye on Rive update.

**Comment by antoniogoulao** [comment]
RiveReactNativeView.kt also fails to compile. I replaced: 
```
        ReadableType.Map -> result.add(this.getMap(i).toMap())
        ReadableType.Array -> result.add(this.getArray(i).toList()) // Recursive conversion
```

by

```
        ReadableType.Map -> result.add(this.getMap(i)?.toMap())
        ReadableType.Array -> result.add(this.getArray(i)?.toList()) // Recursive conversion
```

**Comment by erie-e9** [comment]
Hey guys, experiencing this issue too. Even after following @SurendraSp and @antoniogoulao advices.
Do I missing something? 

"rive-react-native": "^9.2.0",
"react": "19.0.0",
 "react-native": "0.78.1",

Error log:

> Task :rive-react-native:compileDebugKotlin
> Task :rive-react-native:compileDebugKotlin FAILED

**Comment by antoniogoulao** [comment]
@erie-e9 can you post the rest of the log that goes between those 2 Task prints?

```
> Task :rive-react-native:compileReleaseKotlin
e: file:///Users/antonio.goulao/***/app/node_modules/rive-react-native/android/src/main/java/com/rivereactnative/RiveReactNativeView.kt:917:54 Only safe (?.) or non-null asserted (!!.) calls are allowed on a nullable receiver of type 'com.facebook.react.bridge.ReadableMap?'.
e: file:///Users/antonio.goulao/***/app/node_modules/rive-react-native/android/src/main/java/com/rivereactnative/RiveReactNativeView.kt:918:58 Only safe (?.) or non-null asserted (!!.) calls are allowed on a nullable receiver of type 'com.facebook.react.bridge.ReadableArray?'.
e: file:///Users/antonio.goulao/***/app/node_modules/rive-react-native/android/src/main/java/com/rivereactnative/RiveReactNativeViewManager.kt:33:41 None of the following candidates is applicable:
fun mapToRNLoopMode(loopMode: String): RNLoopMode
fun mapToRNLoopMode(riveLoopMode: Loop): RNLoopMode
e: file:///Users/antonio.goulao/***/app/node_modules/rive-react-native/android/src/main/java/com/rivereactnative/RiveReactNativeViewManager.kt:34:60 Argument type mismatch: actual type is 'kotlin.String?', but 'kotlin.String' was expected.
...
> Task :rive-react-native:compileReleaseKotlin FAILED
```

In my case, given the errors above, the 2 workarounds worked for me.

> Hey guys, experiencing this issue too. Even after following [@SurendraSp](https://github.com/SurendraSp) and [@antoniogoulao](https://github.com/antoniogoulao) advices. Do I missing something?
> 
> No Expo - New arch enabled "rive-react-native": "^9.2.0", "react": "19.0.0", "react-native": "0.78.1",
> 
> Error log:
> 
> > Task :rive-react-native:compileDebugKotlin
> > Task :rive-react-native:compileDebugKotlin FAILED

**Comment by AlirezaHadjar** [comment]
[rive-react-native+9.2.0.patch](https://github.com/user-attachments/files/19610422/rive-react-native%2B9.2.0.patch)

this patch did the job for us

**Comment by graphtobinary** [comment]
Hey guys, experiencing this issue too.

**Comment by benjaminkomen** [comment]
Same issue when updating to Expo 53 (and thus React Native from 0.76 to 0.79):
```
[RUN_GRADLEW] > Task :rive-react-native:compileDebugKotlin FAILED
[RUN_GRADLEW] e: file:///private/var/folders/8g/709zppkx53nb4rknsyjs09_00000gn/T/eas-build-local-nodejs/dd9cb3ad-0079-435a-ac02-fc5e4e6ed74f/build/node_modules/rive-react-native/android/src/main/java/com/rivereactnative/RiveReactNativeView.kt:917:54 Only safe (?.) or non-null asserted (!!.) calls are allowed on a nullable receiver of type 'com.facebook.react.bridge.ReadableMap?'.
[RUN_GRADLEW] e: file:///private/var/folders/8g/709zppkx53nb4rknsyjs09_00000gn/T/eas-build-local-nodejs/dd9cb3ad-0079-435a-ac02-fc5e4e6ed74f/build/node_modules/rive-react-native/android/src/main/java/com/rivereactnative/RiveReactNativeView.kt:918:58 Only safe (?.) or non-null asserted (!!.) calls are allowed on a nullable receiver of type 'com.facebook.react.bridge.ReadableArray?'.
[RUN_GRADLEW] e: file:///private/var/folders/8g/709zppkx53nb4rknsyjs09_00000gn/T/eas-build-local-nodejs/dd9cb3ad-0079-435a-ac02-fc5e4e6ed74f/build/node_modules/rive-react-native/android/src/main/java/com/rivereactnative/RiveReactNativeViewManager.kt:33:41 None of the following candidates is applicable:
[RUN_GRADLEW] fun mapToRNLoopMode(loopMode: String): RNLoopMode
[RUN_GRADLEW] fun mapToRNLoopMode(riveLoopMode: Loop): RNLoopMode
[RUN_GRADLEW] e: file:///private/var/folders/8g/709zppkx53nb4rknsyjs09_00000gn/T/eas-build-local-nodejs/dd9cb3ad-0079-435a-ac02-fc5e4e6ed74f/build/node_modules/rive-react-native/android/src/main/java/com/rivereactnative/RiveReactNativeViewManager.kt:34:60 Argument type mismatch: actual type is 'kotlin.String?', but 'kotlin.String' was expected.
[RUN_GRADLEW] e: file:///private/var/folders/8g/709zppkx53nb4rknsyjs09_00000gn/T/eas-build-local-nodejs/dd9cb3ad-0079-435a-ac02-fc5e4e6ed74f/build/node_modules/rive-react-native/android/src/main/java/com/rivereactnative/RiveReactNativeViewManager.kt:35:18 Argument type mismatch: actual type is 'kotlin.String?', but 'kotlin.String' was expected.
[RUN_GRADLEW] e: file:///private/var/folders/8g/709zppkx53nb4rknsyjs09_00000gn/T/eas-build-local-nodejs/dd9cb3ad-0079-435a-ac02-fc5e4e6ed74f/build/node_modules/rive-react-native/android/src/main/java/com/rivereactnative/RiveReactNativeViewManager.kt:52:23 Argument type mismatch: actual type is 'kotlin.String?', but 'kotlin.String' was expected.
[RUN_GRADLEW] e: file:///private/var/folders/8g/709zppkx53nb4rknsyjs09_00000gn/T/eas-build-local-nodejs/dd9cb3ad-0079-435a-ac02-fc5e4e6ed74f/build/node_modules/rive-react-native/android/src/main/java/com/rivereactnative/RiveReactNativeViewManager.kt:52:41 Argument type mismatch: actual type is 'kotlin.String?', but 'kotlin.String' was expected.
[RUN_GRADLEW] e: file:///private/var/folders/8g/709zppkx53nb4rknsyjs09_00000gn/T/eas-build-local-nodejs/dd9cb3ad-0079-435a-ac02-fc5e4e6ed74f/build/node_modules/rive-react-native/android/src/main/java/com/rivereactnative/RiveReactNativeViewManager.kt:63:29 Argument type mismatch: actual type is 'kotlin.String?', but 'kotlin.String' was expected.
[RUN_GRADLEW] e: file:///private/var/folders/8g/709zppkx53nb4rknsyjs09_00000gn/T/eas-build-local-nodejs/dd9cb3ad-0079-435a-ac02-fc5e4e6ed74f/build/node_modules/rive-react-native/android/src/main/java/com/rivereactnative/RiveReactNativeViewManager.kt:63:47 Argument type mismatch: actual type is 'kotlin.String?', but 'kotlin.String' was expected.
[RUN_GRADLEW] e: file:///private/var/folders/8g/709zppkx53nb4rknsyjs09_00000gn/T/eas-build-local-nodejs/dd9cb3ad-0079-435a-ac02-fc5e4e6ed74f/build/node_modules/rive-react-native/android/src/main/java/com/rivereactnative/RiveReactNativeViewManager.kt:74:28 Argument type mismatch: actual type is 'kotlin.String?', but 'kotlin.String' was expected.
[RUN_GRADLEW] e: file:///private/var/folders/8g/709zppkx53nb4rknsyjs09_00000gn/T/eas-build-local-nodejs/dd9cb3ad-0079-435a-ac02-fc5e4e6ed74f/build/node_modules/rive-react-native/android/src/main/java/com/rivereactnative/RiveReactNativeViewManager.kt:74:46 Argument type mismatch: actual type is 'kotlin.String?', but 'kotlin.String' was expected.
[RUN_GRADLEW] e: file:///private/var/folders/8g/709zppkx53nb4rknsyjs09_00000gn/T/eas-build-local-nodejs/dd9cb3ad-0079-435a-ac02-fc5e4e6ed74f/build/node_modules/rive-react-native/android/src/main/java/com/rivereactnative/RiveReactNativeViewManager.kt:84:29 Argument type mismatch: actual type is 'kotlin.String?', but 'kotlin.String' was expected.
[RUN_GRADLEW] e: file:///private/var/folders/8g/709zppkx53nb4rknsyjs09_00000gn/T/eas-build-local-nodejs/dd9cb3ad-0079-435a-ac02-fc5e4e6ed74f/build/node_modules/rive-react-native/android/src/main/java/com/rivereactnative/RiveReactNativeViewManager.kt:84:40 Argument type mismatch: actual type is 'kotlin.String?', but 'kotlin.String' was expected.
[RUN_GRADLEW] e: file:///private/var/folders/8g/709zppkx53nb4rknsyjs09_00000gn/T/eas-build-local-nodejs/dd9cb3ad-0079-435a-ac02-fc5e4e6ed74f/build/node_modules/rive-react-native/android/src/main/java/com/rivereactnative/RiveReactNativeViewManager.kt:95:35 Argument type mismatch: actual type is 'kotlin.String?', but 'kotlin.String' was expected.
[RUN_GRADLEW] e: file:///private/var/folders/8g/709zppkx53nb4rknsyjs09_00000gn/T/eas-build-local-nodejs/dd9cb3ad-0079-435a-ac02-fc5e4e6ed74f/build/node_modules/rive-react-native/android/src/main/java/com/rivereactnative/RiveReactNativeViewManager.kt:95:53 Argument type mismatch: actual type is 'kotlin.String?', but 'kotlin.String' was expected.
[RUN_GRADLEW] e: file:///private/var/folders/8g/709zppkx53nb4rknsyjs09_00000gn/T/eas-build-local-nodejs/dd9cb3ad-0079-435a-ac02-fc5e4e6ed74f/build/node_modules/rive-react-native/android/src/main/java/com/rivereactnative/RiveReactNativeViewManager.kt:106:34 Argument type mismatch: actual type is 'kotlin.String?', but 'kotlin.String' was expected.
[RUN_GRADLEW] e: file:///private/var/folders/8g/709zppkx53nb4rknsyjs09_00000gn/T/eas-build-local-nodejs/dd9cb3ad-0079-435a-ac02-fc5e4e6ed74f/build/node_modules/rive-react-native/android/src/main/java/com/rivereactnative/RiveReactNativeViewManager.kt:106:62 Argument type mismatch: actual type is 'kotlin.String?', but 'kotlin.String' was expected.
[RUN_GRADLEW] e: file:///private/var/folders/8g/709zppkx53nb4rknsyjs09_00000gn/T/eas-build-local-nodejs/dd9cb3ad-0079-435a-ac02-fc5e4e6ed74f/build/node_modules/rive-react-native/android/src/main/java/com/rivereactnative/RiveReactNativeViewManager.kt:137:37 Initializer type mismatch: expected 'kotlin.String', actual 'kotlin.String?'.
[RUN_GRADLEW] e: file:///private/var/folders/8g/709zppkx53nb4rknsyjs09_00000gn/T/eas-build-local-nodejs/dd9cb3ad-0079-435a-ac02-fc5e4e6ed74f/build/node_modules/rive-react-native/android/src/main/java/com/rivereactnative/RiveReactNativeViewManager.kt:137:37 Type mismatch: inferred type is 'kotlin.String?', but 'kotlin.String' was expected.
[RUN_GRADLEW] e: file:///private/var/folders/8g/709zppkx53nb4rknsyjs09_00000gn/T/eas-build-local-nodejs/dd9cb3ad-0079-435a-ac02-fc5e4e6ed74f/build/node_modules/rive-react-native/android/src/main/java/com/rivereactnative/RiveReactNativeViewManager.kt:138:35 Initializer type mismatch: expected 'kotlin.String', actual 'kotlin.String?'.
[RUN_GRADLEW] e: file:///private/var/folders/8g/709zppkx53nb4rknsyjs09_00000gn/T/eas-build-local-nodejs/dd9cb3ad-0079-435a-ac02-fc5e4e6ed74f/build/node_modules/rive-react-native/android/src/main/java/com/rivereactnative/RiveReactNativeViewManager.kt:138:35 Type mismatch: inferred type is 'kotlin.String?', but 'kotlin.String' was expected.
[RUN_GRADLEW] e: file:///private/var/folders/8g/709zppkx53nb4rknsyjs09_00000gn/T/eas-build-local-nodejs/dd9cb3ad-0079-435a-ac02-fc5e4e6ed74f/build/node_modules/rive-react-native/android/src/main/java/com/rivereactnative/RiveReactNativeViewManager.kt:147:37 Initializer type mismatch: expected 'kotlin.String', actual 'kotlin.String?'.
[RUN_GRADLEW] e: file:///private/var/folders/8g/709zppkx53nb4rknsyjs09_00000gn/T/eas-build-local-nodejs/dd9cb3ad-0079-435a-ac02-fc5e4e6ed74f/build/node_modules/rive-react-native/android/src/main/java/com/rivereactnative/RiveReactNativeViewManager.kt:147:37 Type mismatch: inferred type is 'kotlin.String?', but 'kotlin.String' was expected.
[RUN_GRADLEW] e: file:///private/var/folders/8g/709zppkx53nb4rknsyjs09_00000gn/T/eas-build-local-nodejs/dd9cb3ad-0079-435a-ac02-fc5e4e6ed74f/build/node_modules/rive-react-native/android/src/main/java/com/rivereactnative/RiveReactNativeViewManager.kt:148:35 Initializer type mismatch: expected 'kotlin.String', actual 'kotlin.String?'.
[RUN_GRADLEW] e: file:///private/var/folders/8g/709zppkx53nb4rknsyjs09_00000gn/T/eas-build-local-nodejs/dd9cb3ad-0079-435a-ac02-fc5e4e6ed74f/build/node_modules/rive-react-native/android/src/main/java/com/rivereactnative/RiveReactNativeViewManager.kt:148:35 Type mismatch: inferred type is 'kotlin.String?', but 'kotlin.String' was expected.
[RUN_GRADLEW] e: file:///private/var/folders/8g/709zppkx53nb4rknsyjs09_00000gn/T/eas-build-local-nodejs/dd9cb3ad-0079-435a-ac02-fc5e4e6ed74f/build/node_modules/rive-react-native/android/src/main/java/com/rivereactnative/RiveReactNativeViewManager.kt:149:30 Initializer type mismatch: expected 'kotlin.String', actual 'kotlin.String?'.
[RUN_GRADLEW] e: file:///private/var/folders/8g/709zppkx53nb4rknsyjs09_00000gn/T/eas-build-local-nodejs/dd9cb3ad-0079-435a-ac02-fc5e4e6ed74f/build/node_modules/rive-react-native/android/src/main/java/com/rivereactnative/RiveReactNativeViewManager.kt:149:30 Type mismatch: inferred type is 'kotlin.String?', but 'kotlin.String' was expected.
```

**Comment by graphtobinary** [comment]
@liujigang  I've raised a PR (https://github.com/rive-app/rive-react-native/pull/320) to address this issues

**Comment by benjaminkomen** [comment]
Issue can be closed?

**Comment by Elabar** [comment]
I've been using the merged PR as patch previously, and it works flawlessly. 
As the PR is merged and released, I am closing this for now.

**Comment by regalstreak** [comment]
Fix for 
`
node_modules/rive-react-native/android/src/main/java/com/rivereactnative/RiveReactNativeView.kt:809:36 Argument type mismatch: actual type is 'String?', but 'String' was expected.
`



`patches/rive-react-native+9.5.0.patch`
```diff --git a/node_modules/rive-react-native/android/src/main/java/com/rivereactnative/RiveReactNativeView.kt b/node_modules/rive-react-native/android/src/main/java/com/rivereactnative/RiveReactNativeView.kt
index 25746a8..31c4b79 100644
--- a/node_modules/rive-react-native/android/src/main/java/com/rivereactnative/RiveReactNativeView.kt
+++ b/node_modules/rive-react-native/android/src/main/java/com/rivereactnative/RiveReactNativeView.kt
@@ -805,7 +805,7 @@ class RiveReactNativeView(private val context: ThemedReactContext) : FrameLayout
 
         "name" -> {
           if (value.type == ReadableType.String) {
-            val stringValue = value.asString()
+            val stringValue = value.asString()!! 
             DataBindingConfig.Name(stringValue)
           } else null
         }
```
