### ISSUE TITLE
Types broken in 8.5.0: Could not find a declaration file for module 'rive-react-native'

### ISSUE THREAD

**Issue by christophemenager** [rive-app/rive-react-native#311]
When migrating from 8.4.0 to 8.5.0 and running typescript check:

```
error TS7016: Could not find a declaration file for module 'rive-react-native'. 'node_modules/rive-react-native/lib/commonjs/index.js' implicitly has an 'any' type.
  There are types at '/node_modules/rive-react-native/lib/typescript/module/src/index.d.ts', but this result could not be resolved under your current 'moduleResolution' setting. Consider updating to 'node16', 'nodenext', or 'bundler'.

3 import Rive from 'rive-react-native';
```
Everything worked fine with 8.4.0

My tsconfig extends  "expo/tsconfig.base", which has "moduleResolution": "node"

@HayesGordon as you are the top contributor of 8.5.0 and pushed some PR related to the release process: might it be a regression?

**Comment by FTCHD** [comment]
can confirm, probably due to `nodeLinker` as mentioned in #304

**Comment by HayesGordon** [comment]
Thanks for reporting all. I'll close this in favor of #304
